export const products = [
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Nike Air Force 1 NDESTRUKT",
    code: "38BEE270",
    sku: "WW75K5210YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 16.19,
    priceSale: 16.19,
    totalRating: 2.5,
    totalReview: 7794,
    ratings: [
      {
        name: "1 Star",
        starCount: 245,
        reviewCount: 2281,
      },
      {
        name: "2 Star",
        starCount: 6476,
        reviewCount: 8959,
      },
      {
        name: "3 Star",
        starCount: 3477,
        reviewCount: 8269,
      },
      {
        name: "4 Star",
        starCount: 5063,
        reviewCount: 7785,
      },
      {
        name: "5 Star",
        starCount: 1848,
        reviewCount: 3212,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 8062,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 6903,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 1024,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 4207,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 3116,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 6619,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 1696,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9359,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "sale",
    inventoryType: "low_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 93,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 343,
    createdAt: "2022-03-13T05:49:40.476Z",
    category: "Shose",
    gender: "Women",
    colors: ["#00AB55", "#000000"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },

  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
  {
    id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
    cover:
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
    images: [
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_1.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_2.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_3.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_4.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_5.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_6.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_7.jpg",
      "https://storage.googleapis.com/cs-demo-data/coderstore/product_8.jpg",
    ],
    name: "Foundations Matte Flip Flop",
    code: "38BEE271",
    sku: "WW75K5211YW/SV",
    tags: [
      "Dangal",
      "The Sting",
      "2001: A Space Odyssey",
      "Singin' in the Rain",
    ],
    price: 35.71,
    priceSale: null,
    totalRating: 2,
    totalReview: 1063,
    ratings: [
      {
        name: "1 Star",
        starCount: 995,
        reviewCount: 6584,
      },
      {
        name: "2 Star",
        starCount: 4552,
        reviewCount: 1803,
      },
      {
        name: "3 Star",
        starCount: 2967,
        reviewCount: 8697,
      },
      {
        name: "4 Star",
        starCount: 2903,
        reviewCount: 654,
      },
      {
        name: "5 Star",
        starCount: 935,
        reviewCount: 8274,
      },
    ],
    reviews: [
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b1",
        name: "Jayvion Simon",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_1.jpg",
        comment: "Assumenda nam repudiandae rerum fugiat vel maxime.",
        rating: 2.5,
        isPurchased: true,
        helpful: 3588,
        postedAt: "2022-03-13T05:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b2",
        name: "Lucian Obrien",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_2.jpg",
        comment: "Quis veniam aut saepe aliquid nulla.",
        rating: 2,
        isPurchased: true,
        helpful: 3087,
        postedAt: "2022-03-12T04:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b3",
        name: "Deja Brady",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_3.jpg",
        comment: "Reprehenderit ut voluptas sapiente ratione nostrum est.",
        rating: 4.9,
        isPurchased: true,
        helpful: 2419,
        postedAt: "2022-03-11T03:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b4",
        name: "Harrison Stein",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_4.jpg",
        comment: "Error ut sit vel molestias velit.",
        rating: 2,
        isPurchased: false,
        helpful: 9933,
        postedAt: "2022-03-10T02:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b5",
        name: "Reece Chung",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_5.jpg",
        comment: "Quo quia sit nihil nemo doloremque et.",
        rating: 4,
        isPurchased: false,
        helpful: 1792,
        postedAt: "2022-03-09T01:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b6",
        name: "Lainey Davidson",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_6.jpg",
        comment: "Autem doloribus harum vero laborum.",
        rating: 5,
        isPurchased: true,
        helpful: 2520,
        postedAt: "2022-03-08T00:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b7",
        name: "Cristopher Cardenas",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_7.jpg",
        comment:
          "Tempora officiis consequuntur architecto nostrum autem nam adipisci.",
        rating: 4.9,
        isPurchased: false,
        helpful: 2927,
        postedAt: "2022-03-06T23:49:40.476Z",
      },
      {
        id: "e99f09a7-dd88-49d5-b1c8-1daf80c2d7b8",
        name: "Melanie Noble",
        avatarUrl:
          "https://storage.googleapis.com/cs-demo-data/coderstore/avatar_8.jpg",
        comment: "Voluptas sunt magni adipisci praesentium saepe.",
        rating: 5,
        isPurchased: false,
        helpful: 9305,
        postedAt: "2022-03-05T22:49:40.476Z",
      },
    ],
    status: "",
    inventoryType: "out_of_stock",
    sizes: [
      "6",
      "7",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
    ],
    available: 2,
    description:
      "\n<p><strong><small> SPECIFICATION</small></strong></p>\n<p>Leather panels. Laces. Rounded toe. Rubber sole.\n<br /><br />\n<p><strong><small> MATERIAL AND WASHING INSTRUCTIONS</small></strong></p>\n<p>Shoeupper: 54% bovine leather,46% polyurethane. Lining: 65% polyester,35% cotton. Insole: 100% polyurethane. Sole: 100% thermoplastic. Fixing sole: 100% glued.</p>\n",
    sold: 582,
    createdAt: "2022-03-12T04:49:40.476Z",
    category: "Shose",
    gender: "Kids",
    colors: ["#000000", "#FFFFFF"],
  },
];
